#!/bin/bash
export orig_dir=`pwd`

filed=$orig_dir/WORK*/changelog.txt

if [ -e /usr/bin/kate ] 
then
  echo "Opening Kate text editor"  
  kate $filed
elif [ -e /usr/bin/gedit ] 
then
  echo "Opening Gedit text editor"    
  gedit $filed
else
  echo "Did not find a suitable compatible editor. Aborting"
fi

exit 0
