#!/bin/bash
echo "Current working directory $(pwd)"
maindir=$(pwd)

if [ $1="main" ]
then
  echo "Editing Main Menu"
  filed="$maindir/menu"
else
  echo "Editing Advanced Menu"
  filed="$maindir/scripts/menu_advanced"
fi

if [ -e /usr/bin/kate ] 
then
  echo "Found kate"  
  kate $filed
elif [ -e /usr/bin/gedit ] 
then
  echo "Found Gedit"
  gedit $filed
else
  echo "Did not find a suitable compatible editor. Aborting"
fi
read something_1
exit 0

  
  
